controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (KARINA.vy == 0) {
        KARINA.vy = -100
    }
})
let patito_proz: Sprite = null
let KARINA: Sprite = null
scene.setBackgroundColor(9)
KARINA = sprites.create(img`
    . . . . . f f 4 4 f f . . . . . 
    . . . . f 5 4 5 5 4 5 f . . . . 
    . . . f e 4 5 5 5 5 4 e f . . . 
    . . f b 3 e 4 4 4 4 e 3 b f . . 
    . . f 3 3 3 3 3 3 3 3 3 3 f . . 
    . f 3 3 e b 3 e e 3 b e 3 3 f . 
    . f 3 3 f f e e e e f f 3 3 f . 
    . f b b f b f e e f b f b b f . 
    . f b b e 1 f 4 4 f 1 e b b f . 
    f f b b f 4 4 4 4 4 4 f b b f f 
    f b b f f f e e e e f f f b b f 
    . f e e f b d d d d b f e e f . 
    . . e 4 c d d d d d d c 4 e . . 
    . . e f b d b d b d b b f e . . 
    . . . f f 1 d 1 d 1 d f f . . . 
    . . . . . f f b b f f . . . . . 
    `, SpriteKind.Player)
controller.moveSprite(KARINA, 100, 0)
tiles.setCurrentTilemap(tilemap`level1`)
KARINA.ay = 90
scene.cameraFollowSprite(KARINA)
for (let value of tiles.getTilesByType(assets.tile`myTile8`)) {
    patito_proz = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . f f f f . . . . . . . . 
        . . . f 5 5 5 5 f . . . . . . . 
        . . . f 5 f 5 5 f . . . . . . . 
        . f f 4 5 5 5 5 5 f . . . . . . 
        f 4 4 4 5 5 5 5 5 f . . . . . . 
        . f 4 4 4 5 5 5 5 f . . . . . . 
        . . f f 5 5 5 5 f . . . f . . . 
        . . f 5 5 5 5 f . . . f 5 f . . 
        . f 5 5 5 5 5 5 f f f 5 5 f . . 
        . f 5 5 5 5 5 5 5 5 5 5 5 f . . 
        . f 5 5 5 4 5 5 5 5 5 4 5 f . . 
        . f 5 5 5 5 4 5 5 5 4 5 5 f . . 
        . . f 5 5 5 5 4 4 4 5 5 f . . . 
        . . . f 5 5 5 5 5 5 5 f . . . . 
        . . . . f f f f f f f . . . . . 
        `, SpriteKind.Player)
    animation.runImageAnimation(
    patito_proz,
    [img`
        ..........................
        ..........................
        .......ffff...............
        ......f5555f..............
        ......f55555f.............
        ....ff455f55f.............
        ...f44455555f.............
        ....f444555f...f..........
        .....ff555f...f5f.........
        .....f55555fff55f.........
        ....f55555555555f.........
        ....f55555555555f.........
        ....f55555555555f.........
        .....f555555555f..........
        ......f5555555f...........
        .......fffffff............
        ......fff...fff...........
        ....fff4f...f4fff.........
        ....f444f...f444f.........
        ....fffff...fffff.........
        ..........................
        ..........................
        ..........................
        ..........................
        ..........................
        ..........................
        `],
    500,
    false
    )
}
